# Generated by Django 4.1.1 on 2022-09-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('price', models.FloatField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('type', models.CharField(choices=[('Bedroom', 'Bedroom'), ('Hotel', 'Hotel'), ('Office', 'Office'), ('Living room', 'Living room'), ('Hospital', 'Hospital')], default='Bedroom', max_length=100)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.property')),
            ],
        ),
    ]
