# Generated by Django 4.1.1 on 2022-09-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'), ('LivingRoom', 'LivingRoom'), ('Reausturant', 'Reausturant')], default='Bedroom', max_length=100),
        ),
    ]
